behaviors:
  MoveToShow:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 4096
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.97
        strength: 1.0
              gail:
        strength: 0.5
        demo_path: Demos/Arena.demo
    behavioral_cloning:
      strength: 0.5
      demo_path: Demos/Arena.demo
    max_steps: 1000000000
    time_horizon: 128
    summary_freq: 20000